### ISSUE TITLE
No login possible "Es gibt einen Fehler. Bitte versuchen Sie es später noch einmal"

### ISSUE THREAD

**Issue by scharfan1990** [Haxe18/telekom_fon_connect#3]
Hi
eine Zeitlang hat das Skript super funktioniert. Nun kommt immer der Fehler "Es gibt einen Fehler. Bitte versuchen Sie es später noch einmal" und die Hotspot page erscheint aber leider kein Feld zum Login.
Ich verwendet einen Raspberry mit Raspbian.
Auf meinem Handy und MacBook funktioniert der Login komischerweise ohne Probleme.

Da ich leider keine Lösung finden konnte.
Bitte ich hier um Hilfe
Danke
Grüße

**Comment by Haxe18** [comment]
Hi @scharfan1990 ,

diese Meldung sagt mir gar nichts und kommt dann vermutlich auch nicht von meinem Script.

Du loggst dich also via Script ein, es scheint erfolgreich, aber wenn du dann im Browser eine Seite öffnest, dann kommt diese Meldung mit der Hotspot-Login Seite ?

Oder klappt schon der Login via Script nicht ?

**Comment by feliche93** [comment]
Hi @Haxe18, vielen Dank für das coole Projekt. Ich habe auch gerade versucht das ganze zum Laufen zu bekommen und hatte auch folgendes Problem. Wie beschrieben habe ich folgenden Command ausgeführt:

`python telekom_fon_connect.py -c"/Users/felix/Downloads/telekom_fon_connect-master/telekom_fon_connect.conf" -v`

und habe dann folgenden Error bekommen:

2019-11-02 16:11:59,377 DEBUG Working with configfile: /Users/felix/Downloads/telekom_fon_connect-master/telekom_fon_connect.conf
2019-11-02 16:11:59,377 INFO log_level is : DEBUG
2019-11-02 16:11:59,388 DEBUG Starting new HTTP connection (1): online-status.cf:80
2019-11-02 16:11:59,390 ERROR An error occurred when doing the request, will exit now. Please try again later
2019-11-02 16:11:59,390 DEBUG HTTPConnectionPool(host='online-status.cf', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1046696d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Wenn du weitere Infos brauchst, schreib mir gerne, würde mich sehr freuen wenn wir das Script zum Laufen bekommen könnten. Danke!

**Comment by Haxe18** [comment]
Hi @feliche93,

die Fehlermeldung lässt auf Probleme beim Auflösen der URL _online-status.cf_ schließen, in diese Richtung müsse man mal gehen, warum es im Browser geht und in python dann scheinbar nicht.
Du kannst gerne mal im Terminal mit einem 

> curl -I  www.online-status.cf

prüfen ob du eine HTTP 302 Umleitung auf die Hostspot Login Seite bekommst.
Wenn ich diese Meldung mal google, finde ich viele Leute mit diesem Problem unter MacOS.
Leider habe ich selbst kein Mac Gerät um zu Testen und auch aktuell keinen Hotspot in der Nähe um zu prüfen ob es unter Linux überhaupt noch funktioniert :(
Ende August dieses Jahres tat das Script auf meinem Raspberry PI mit Debian Buster und Python3 noch wunderbar.

**Comment by Haxe18** [comment]
Da sich niemand mehr meldet, zu mit dem Thema.
